### PR TITLE
forced logout when connection is dropped

### PR DESCRIPTION
**Pull request by aabidshamji**

### CODE REVIEW

**Comment by compnerd** [comment]
Please reindent the code, the style is 2 space indents.

**Comment by aabidshamji** [comment]
done

**Comment by compnerd** [comment]
There are a lot of additional unrelated changes.  Could you please clean up the change?

**Comment by samisuteria** [comment]
closing this in favor of this: https://github.com/AgaKhanFoundation/WCF-iOS/pull/340

**Pull request closed without merging**
